src/Entity/Pin.php
<?php

namespace App\Entity;

use App\Repository\PinRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PinRepository::class)
 * @ORM\Table(name="pins")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */

class Pin
{

    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le Titre ne peut pas être vide")
     * @Assert\Length(min=3,minMessage="Le Titre doit faire plus de 3 caractéres")
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="La description ne peut pas être vide")
     * @Assert\Length(min=10,minMessage="La description doit faire plus de 10 caractéres")
     */
    private $Description;


    /**
     * @Vich\UploadableField(mapping="pin_image", fileNameProperty="imageName")
     * @Assert\Image(maxSize="8M",maxSizeMessage="La taille maximum de l'image doit être de 8mega")
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pins")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @param File|UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Traits\Timestampable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    use Timestampable;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Veuillez entrer votre adresse Email")
     * @Assert\Email(message="Veuillez rentrer une adresse E-mail valide")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     *
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez entrer votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez entrer votre nom")
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Pin::class, mappedBy="user", orphanRemoval=true)
     */
    private $pins;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function __construct()
    {
        $this->pins = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Pin[]
     */
    public function getPins(): Collection
    {
        return $this->pins;
    }

    public function addPin(Pin $pin): self
    {
        if (!$this->pins->contains($pin)) {
            $this->pins[] = $pin;
            $pin->setUser($this);
        }

        return $this;
    }

    public function removePin(Pin $pin): self
    {
        if ($this->pins->removeElement($pin)) {
            // set the owning side to null (unless already changed)
            if ($pin->getUser() === $this) {
                $pin->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName() : string
    {
        return $this->getFirstName()." ".$this->getLastName();
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getGravatarUrl(?int $size=100)
    {
        return sprintf('https://www.gravatar.com/avatar/%s/?s=%d',md5(strtolower(trim($this->getEmail()))),'?s='.$size);
    }
}

src/Form/PinType.php
<?php

namespace App\Form;

use App\Entity\Pin;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;

class PinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageFile', VichImageType::class, [
                'label' => 'Image (JPEG ou PNG)',
                'required' => false,
                'allow_delete' => true,
                'download_uri' => false,
                'imagine_pattern' => 'squared_thumbnail_small'
            ])

            ->add('title', TextType::class)

            ->add('Description', TextareaType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pin::class,
        ]);
    }
}

src/Controller/PinsController.php
<?php

namespace App\Controller;

use App\Entity\Pin;
use App\Form\PinType;
use App\Repository\PinRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PinsController extends AbstractController
{
    /**
     * @Route("/", name="app_home", methods={"GET"})
     * @param PinRepository $pinRepository
     * @return Response
     */
    public function index(PinRepository $pinRepository, UserRepository $userRepo): Response
    {
        $pins = $pinRepository->findBy([],['createdAt' => 'DESC']);
        $user = $this->getUser();
        return $this->render('pins/index.html.twig', compact('pins','user'));

    }

    /**
     * @Route("/pins/create", name="app_pins_create", methods={"GET","PUT"})
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     * @Security("is_granted('ROLE_USER') && user.isVerified()")
     */

    public function create(Request $request, EntityManagerInterface $em, UserRepository $userRepo) : Response
    {
        $pin = new Pin;

        $form = $this->createForm(PinType::class, $pin,
            [
                'method' => 'PUT'
            ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $pin->setUser($this->getUser());
            $em->persist($pin);
            $em->flush();

            $this->addFlash('success','Le pin a été créé !');

            return $this->redirectToRoute("app_home");
        }

        return $this->render('pins/create.html.twig',
            [
                'form' => $form->createView()
            ]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_show", methods={"GET"})
     * @param Pin $pin
     * @return Response
     */
    public function show(Pin $pin) : Response
    {
        return $this->render('pins/show_pin.html.twig', compact('pin'));
    }

    /**
     * @Route("/pins/{id<[0-9]+>}/edit", name="app_pins_edit", methods={"GET","PUT"})
     * @param Pin $pin
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     * @IsGranted("PIN_MANAGE",subject="pin")
     */
    public function edit(Pin $pin, Request $request, EntityManagerInterface $em) : Response
    {
        $form = $this->createForm(PinType::class, $pin,
        [
            'method' => 'PUT'
        ]);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $em->flush();

            $this->addFlash('success','Le pin a été modifié!');

            return $this->redirectToRoute("app_home");
        }

        return $this->render('pins/edit_pin.html.twig',
            [
                'pin' => $pin,
                'form' => $form->createView()
            ]);
    }

    /**
     * @Route("/pins/{id<[0-9]+>}", name="app_pins_delete", methods={"DELETE"})
     * @param Request $req
     * @param Pin $pin
     * @param EntityManagerInterface $em
     * @return Response
     * @IsGranted("PIN_MANAGE",subject="pin")
     */
    public function delete(Request $req,Pin $pin, EntityManagerInterface $em) : Response
    {
        if($this->isCsrfTokenValid('pin_deletion_'.$pin->getId(),$req->request->get('csrf_token')))
        {
            $em->remove($pin);
            $em->flush();

            $this->addFlash('info','Le pin a bien été supprimé!');
        }

        return $this->redirectToRoute('app_home');
    }
}

templates/pins/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
    <input class="btn btn-primary btn-block" type="submit" value="{{ submitButtonText ?? ('Créer le Pin') }}">
{{ form_end(form) }}

templates/pins/create.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title "Panterest | Nouveau Pin" %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1> Crée le Pin </h1>
            <article>
                {{ include('pins/_form.html.twig') }}
            </article>
        </div>
    </div>

{% endblock %}

templates/pins/edit_pin.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title "Pinterest | Edit Pin #" ~ pin.id %}

{% block body %}
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h1> Editer le Pin </h1>
            <article>

            {{ include('pins/_form.html.twig', {submitButtonText:'Editer le Pin'}) }}

            </article>
        </div>
    </div>


{% endblock %}

templates/pins/index.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title "Pinterest | Acceuil" %}

{% block body %}

    {% if pins|length > 0 %}

    <h1 class="mb-4 text-center text-muted">{{ pluralize(pins|length, 'Pin') }} </h1>

        {% for row in pins|batch(3) %}
        <div class="row mb-5">
            {% for pin in row %}
                <div class="col-md-4">
                    <article class="pin bg-white rounded shadow">
                        <div class="mw-100 overflow-hidden rounded-top">
                            <a href="{{ path('app_pins_show', {id: pin.id}) }}">
                                <img src="{{ (pin.imageName ? vich_uploader_asset(pin) :asset('build/images/placeholder.jpeg')) |imagine_filter('squared_thumbnail_medium') }}" alt="{{ pin.title }}" class="w-100"/>
                            </a>
                        </div>
                        <h2 class="h5 pl-3 pt-3">
                            <a href="{{ path('app_pins_show', {id: pin.id}) }}" class="text-secondary text-decoration-none">{{ pin.title }}</a>
                        </h2>
                        <p class="text-muted pl-3 pb-3"><small>Crée par {{ pin.user.fullName }}</small></p>
                    </article>
                </div>

            {% endfor %}
        </div>
        {% endfor %}
    {% else %}

        <article class="mt-5">
            <h1 class="text-center">Il n'y a pas de Pin</h1>
            <p class="text-center"> <a href="{{ path('app_pins_create') }}">Crée le premier!</a></p>
        </article>

    {% endif %}

{% endblock %}

templates/pins/show_pin.html.twig
{% extends 'layouts/base.html.twig' %}

{% block title "Pinterest | Acceuil" %}

{% block body %}

    <div class="row">
        <div class="col-md-6 mx-auto">

            <article class="pin bg-white rounded shadow">
                <div class="mw-100 overflow-hidden rounded-top">
                        <img src="{{ (pin.imageName ? vich_uploader_asset(pin) :asset('build/images/placeholder.jpeg')) |imagine_filter('squared_thumbnail_medium') }}" alt="{{ pin.title }}" class="w-100"/>
                </div>

                <div class="p-3">

                    <h1 class="h5">
                        <p class="text-secondary text-center">{{ pin.title }}</p>
                    </h1>
                    <p class="text-muted d-flex justify-content-between align-content-center">
                        <small>Crée par {{ pin.user.fullName }}</small>
                        |
                        <time datetime="{{ pin.createdAt|date('d-m-Y H:i:s') }}">{{ pin.createdAt|ago(locale='fr') }}</time>
                    </p>

                    <p class="text-break pt-3 text-center">
                        {{ pin.description }}
                    </p>

                    {% if is_granted('PIN_MANAGE', pin) %}
                    <div class="pt-3">

                        <a
                            href="#" onclick="event.preventDefault();
                            confirm('Etes vous sûr de vouloir supprimer ce pin?') &&
                            document.getElementById('js-pin-delete-form').submit()"
                            class="btn btn-danger">
                            Supprimer le Pin
                        </a>

                        <a
                            href="{{ path('app_pins_edit', {'id' : pin.id}) }}"
                            class="btn btn-light">
                            Editer le Pin
                        </a>

                        <form id="js-pin-delete-form" action="{{ path('app_pins_delete',{ 'id' : pin.id}) }}" method="POST" style="display: none">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token('pin_deletion_'~pin.id) }}">
                            <input type="hidden" name="_method" value="DELETE">
                        </form>
                    </div>
                    {% endif %}
                </div>

            </article>

        </div>
    </div>
{% endblock %}